# Generated by Django 4.0.4 on 2022-05-14 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantesd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudantes',
            name='cod_curso',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='estudantes',
            name='cor',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='estudantes',
            name='escola',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='estudantes',
            name='motivacao',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estudantes',
            name='renda',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='estudantes',
            name='sexo',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='RA',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
