# Generated by Django 4.0.4 on 2022-05-14 19:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estudantesd', '0002_estudantes_cod_curso_estudantes_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudantes',
            name='site_username',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='CEP',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='Email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='Nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='RA',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='cod_curso',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='cor',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='escola',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='motivacao',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='renda',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='sexo',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
    ]
