# Generated by Django 4.0.4 on 2022-05-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantesd', '0003_estudantes_site_username_alter_estudantes_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudantes',
            name='sol_feita',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='CEP',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='Email',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='Nome',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='estudantes',
            name='RA',
            field=models.CharField(blank=True, default=None, max_length=255, unique=True),
        ),
    ]
