# Generated by Django 4.0.4 on 2022-05-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantesd', '0005_remove_estudantes_site_username_alter_estudantes_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(default=None, max_length=255)),
                ('RA', models.CharField(default=None, max_length=255, unique=True)),
                ('Email', models.CharField(default=None, max_length=255)),
                ('Notebook', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Deferida', models.BooleanField(default=None)),
                ('Mensagem', models.CharField(default=None, max_length=255)),
                ('EmailEnviado', models.BooleanField(default=None)),
            ],
        ),
    ]
